### PR TITLE
fix(FR-3360): bump sharp to ^0.35.1 to restore docs-toolkit type resolution

### LINKED ISSUE #8369: sharp 0.35.0 breaks docs-toolkit tsc build (missing types condition in exports)
Dependabot PR #8339 (commit `12d175bc8`) bumped `sharp` from 0.34.5 to 0.35.0 in `packages/backend.ai-docs-toolkit`. The commit is on `main`, so every build path that compiles the toolkit is currently broken — including the AWS Amplify webui deploy.

## Why This Work is Needed

`pnpm run build` fails at `packages/backend.ai-docs-toolkit build$ tsc`:

```
src/image-optimizer.ts(43,34): error TS7016: Could not find a declaration file for module "sharp".
  .../node_modules/sharp/dist/index.mjs implicitly has an "any" type.
  There are types at .../node_modules/sharp/lib/index.d.ts, but this result could not be
  resolved when respecting package.json "exports".
```

sharp 0.35.0 introduced an `exports` field for the first time but omitted the `types` condition:

```json
"exports": { ".": { "import": "./dist/index.mjs", "require": "./dist/index.cjs" } },
"types": "./lib/index.d.ts"
```

The toolkit tsconfig uses `moduleResolution: "bundler"`, which honors `exports`, so the top-level `types` is ignored, `sharp` resolves to `dist/index.mjs`, and no declaration file is found. sharp 0.34.5 shipped no `exports` field at all, so the top-level `types` applied and resolution worked. Reproducible locally — not an Amplify-specific or CI-cache issue.

Blast radius:

- Amplify **webui** app (`appRoot: react`) — runs root `pnpm run build`, which recurses into the toolkit. Deploy failing.
- Amplify **docs** app (`appRoot: packages/backend.ai-webui-docs`) — preBuild runs `pnpm --filter backend.ai-docs-toolkit run build`.
- Any CI job that builds the toolkit.

Upstream fixed this in sharp **0.35.1** by adding per-condition `types` entries pointing at `dist/index.d.mts` / `dist/index.d.cts`.

## Expected Outcomes

- `sharp` devDependency bumped to `^0.35.1` (resolves to 0.35.3, published 2026-07-01 — outside the 7-day `minimumReleaseAge` quarantine, so no `minimumReleaseAgeExclude` entry needed)
- Optional peer range widened to `^0.34.0 || ^0.35.1` (the existing `^0.34.0` was already unsatisfied by the 0.35.0 devDependency)
- `src/image-optimizer.ts`: sharp 0.35 ships real ESM whose module namespace is not callable — the constructor is the default export. `type SharpModule = typeof import("sharp")` becomes `(typeof import("sharp"))["default"]`; without this the version bump alone produces TS2352 and TS2349
- `bash scripts/verify.sh` ends with `=== ALL PASS ===`, `pnpm run build` emits `build/web/`, and `pnpm install --frozen-lockfile` is a no-op

### PR DESCRIPTION
**Pull request by yomybaby**
Resolves #8369 ([FR-3360](https://lablup.atlassian.net/browse/FR-3360))

## Summary

`main` is currently red: `pnpm run build` fails at `packages/backend.ai-docs-toolkit build$ tsc`, which fails the AWS Amplify webui deploy. Regression from #8339 (Dependabot, `12d175bc8`) bumping `sharp` 0.34.5 → 0.35.0.

```
src/image-optimizer.ts(43,34): error TS7016: Could not find a declaration file for module 'sharp'.
  .../node_modules/sharp/dist/index.mjs implicitly has an 'any' type.
  There are types at .../node_modules/sharp/lib/index.d.ts, but this result could not be
  resolved when respecting package.json "exports".
```

**Root cause** — sharp 0.35.0 introduced an `exports` field for the first time but omitted the `types` condition:

```json
"exports": { ".": { "import": "./dist/index.mjs", "require": "./dist/index.cjs" } },
"types": "./lib/index.d.ts"
```

The toolkit tsconfig uses `moduleResolution: "bundler"`, which honors `exports`, so the top-level `types` is ignored, `sharp` resolves to `dist/index.mjs`, and tsc finds no declaration file. sharp 0.34.5 shipped no `exports` field at all, so the top-level `types` applied and resolution worked. This reproduces locally — it is not an Amplify-specific or CI-cache problem.

**Blast radius** — the toolkit is built on three paths, all broken:

| Path | Command |
|---|---|
| Amplify **webui** app (`appRoot: react`) | root `pnpm run build` → `pnpm run -r --stream build` recurses into the toolkit |
| Amplify **docs** app (`appRoot: packages/backend.ai-webui-docs`) | preBuild `pnpm --filter backend.ai-docs-toolkit run build` |
| CI | any job that builds the toolkit |

## Changes

Upstream fixed this in sharp **0.35.1** by adding per-condition `types` entries pointing at `dist/index.d.mts` / `dist/index.d.cts`.

- **`package.json`** — devDependency `^0.35.0` → `^0.35.1` (resolves to 0.35.3, published 2026-07-01, so it is outside the 7-day `minimumReleaseAge` quarantine and needs no `minimumReleaseAgeExclude` entry). Optional peer range widened `^0.34.0` → `^0.34.0 || ^0.35.1`; the old range was already unsatisfied by the 0.35.0 devDependency.
- **`src/image-optimizer.ts`** — the version bump alone is **not** sufficient. sharp 0.35 ships real ESM whose module namespace is not callable; the constructor is the default export. Left as-is, the bump trades TS7016 for TS2352 (at the `as SharpModule` cast) and TS2349 (at the `sharp(sourceBuf)` call). `SharpModule` now resolves the default export: `(typeof import("sharp"))["default"]`. The `?? mod` fallback in `loadSharp` still covers the older CJS shape, so the widened peer range stays honest.
- **`pnpm-lock.yaml`** — regenerated; contains only the sharp 0.35.3 and `@img/sharp-*` platform-binary updates.

## Verification

| Check | Result |
|---|---|
| `bash scripts/verify.sh` | `=== ALL PASS ===` |
| **`pnpm run build`** (the failing command) | passes, emits `build/web/` |
| `pnpm --filter backend.ai-docs-toolkit run build` (Amplify docs preBuild) | passes |
| `pnpm install --frozen-lockfile` | `Already up to date` |
| `tsc --noEmit` in `packages/backend.ai-docs-toolkit` | passes |
| `tsx --test src/image-optimizer.test.ts` | 13/13 pass |
| sharp 0.35.3 runtime smoke (WebP + AVIF encode via `mod.default`) | passes |

[FR-3360]: https://lablup.atlassian.net/browse/FR-3360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by yomybaby** [comment]
* **#8370** <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/8370?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/lablup/backend.ai-webui/8370?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>flow:merge-queue</kbd> - adds this PR to the back of the merge queue
- <kbd>flow:hotfix</kbd> - for urgent changes, fast-track this PR to the front of the merge queue

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/lablup?ref=merge-queue-instructions-in-stack-comment&prId=8370).

<h2></h2>
<sub>

An organization admin has required the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
